---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: toy-develop
spec:
  releaseName: toy-develop-mariadb
  chart:
    # https://github.com/helm/charts/tree/master/stable/mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    name: mariadb
    version: 6.12.0  # MariaDB 10.3.18
  resetValues: true
  values:
    fullnameOverride: mariadb

    rootUser:
      password: changeit  # for development only

    db:
      user: geograph
      password: changeit  # for development only
      name: geograph_toy

    replication:
      enabled: false

    master:
      # Override character set and collation to latin1/swedish_ci
      config: |-
        [mysqld]
        skip-name-resolve
        explicit_defaults_for_timestamp
        basedir=/opt/bitnami/mariadb
        port=3306
        socket=/opt/bitnami/mariadb/tmp/mysql.sock
        tmpdir=/opt/bitnami/mariadb/tmp
        max_allowed_packet=16M
        bind-address=0.0.0.0
        pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
        log-error=/opt/bitnami/mariadb/logs/mysqld.log
        character-set-server=latin1
        collation-server=latin1_swedish_ci

        [client]
        port=3306
        socket=/opt/bitnami/mariadb/tmp/mysql.sock
        default-character-set=latin1

        [manager]
        port=3306
        socket=/opt/bitnami/mariadb/tmp/mysql.sock
        pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

# vim: ts=2 sw=2 et sts=2 ft=yaml
